AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Simple ToDo API (Lambda + API Gateway + DynamoDB)

Globals:
  Function:
    Runtime: python3.10
    Timeout: 10
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref TodosTable

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      TracingEnabled: true
      Cors:
        AllowMethods: "'GET,POST,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  TodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: application.handler
      CodeUri: .
      Events:
        GetTodos:
          Type: Api
          Properties:
            Path: /todos
            Method: GET
            RestApiId: !Ref ApiGateway
        CreateTodo:
          Type: Api
          Properties:
            Path: /todos
            Method: POST
            RestApiId: !Ref ApiGateway
        DeleteTodo:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: DELETE
            RestApiId: !Ref ApiGateway
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodosTable

  TodosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: Invoke URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev"
